global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # CopilotOS API metrics
  - job_name: 'copilotos-api'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/api/metrics'
    scheme: 'http'

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # OTEL Collector
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']