#!/usr/bin/env bash
################################################################################
# preflight.sh - Docker Compose Preflight Check
#
# Checks service health with throttling and conditional execution.
# Reads configuration from .claude/.env.claude (generated by session_start.sh).
#
# Behavior:
#   - Skips if COMPOSE_FILE is empty (repo-only mode)
#   - Skips if throttle period hasn't elapsed (default 15s)
#   - Skips if PREFLIGHT_SERVICES is empty (opt-in mode)
#   - Writes results to docs/agent/preflight.md
#
# Exit codes:
#   0 - All checks passed (or skipped)
#   2 - Infrastructure failure (services not healthy)
################################################################################
set -euo pipefail

# ============================================================================
# PATHS AND CONFIG
# ============================================================================

root_dir="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$root_dir"

env_file="$root_dir/.claude/.env.claude"
throttle_file="$root_dir/.claude/.preflight_last_run"
output_file="$root_dir/.claude/docs/preflight.md"

# ============================================================================
# LOAD ENV (with defaults)
# ============================================================================

# shellcheck disable=SC1090
if [[ -f "$env_file" ]]; then
  # Source only specific vars to avoid conflicts
  while IFS='=' read -r key value; do
    case "$key" in
      COMPOSE_FILE|COMPOSE_PROJECT_NAME|PREFLIGHT_SERVICES|PREFLIGHT_THROTTLE_SECONDS)
        # Remove quotes if present
        value="${value%\"}"
        value="${value#\"}"
        export "$key=$value"
        ;;
    esac
  done < <(grep -E "^[A-Z_]+=" "$env_file" 2>/dev/null || true)
fi

# Defaults
COMPOSE_FILE="${COMPOSE_FILE:-}"
COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-}"
PREFLIGHT_SERVICES="${PREFLIGHT_SERVICES:-}"
PREFLIGHT_THROTTLE_SECONDS="${PREFLIGHT_THROTTLE_SECONDS:-15}"

# ============================================================================
# EARLY EXIT CONDITIONS
# ============================================================================

# Exit if no compose file (repo-only mode)
if [[ -z "$COMPOSE_FILE" ]]; then
  echo "preflight: skip (no COMPOSE_FILE)" >&2
  exit 0
fi

# Exit if compose file doesn't exist
if [[ ! -f "$root_dir/$COMPOSE_FILE" ]]; then
  echo "preflight: skip (COMPOSE_FILE not found: $COMPOSE_FILE)" >&2
  exit 0
fi

# Exit if no services configured for preflight
if [[ -z "$PREFLIGHT_SERVICES" ]]; then
  echo "preflight: skip (PREFLIGHT_SERVICES empty)" >&2
  exit 0
fi

# ============================================================================
# THROTTLE CHECK
# ============================================================================

now=$(date +%s)

if [[ -f "$throttle_file" ]]; then
  last_run=$(cat "$throttle_file" 2>/dev/null || echo "0")
  elapsed=$((now - last_run))

  if [[ $elapsed -lt $PREFLIGHT_THROTTLE_SECONDS ]]; then
    echo "preflight: throttled (${elapsed}s < ${PREFLIGHT_THROTTLE_SECONDS}s)" >&2
    exit 0
  fi
fi

# Update throttle timestamp
echo "$now" > "$throttle_file"

# ============================================================================
# PREFLIGHT CHECKS
# ============================================================================

mkdir -p "$(dirname "$output_file")"

# Check if docker compose is available
if ! docker compose -f "$root_dir/$COMPOSE_FILE" config --services >/dev/null 2>&1; then
  echo "preflight: docker compose unavailable" >&2
  {
    echo "# Preflight Report"
    echo ""
    echo "**Status:** SKIP"
    echo "**Reason:** Docker compose unavailable"
    echo "**Time:** $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  } > "$output_file"
  exit 0
fi

# Get available services from compose
available_services=$(docker compose -f "$root_dir/$COMPOSE_FILE" config --services 2>/dev/null)

status=0
results=()

echo "preflight: checking services" >&2

# Convert space-separated string to array
IFS=' ' read -ra services_array <<< "$PREFLIGHT_SERVICES"

for svc in "${services_array[@]}"; do
  # Skip if service not in compose file
  if ! echo "$available_services" | grep -qx "$svc"; then
    results+=("| $svc | skip | not in compose |")
    echo "preflight: skip $svc (not in compose)" >&2
    continue
  fi

  # Check if container is running
  container_id=$(docker ps -q \
    --filter "label=com.docker.compose.service=$svc" \
    --filter "label=com.docker.compose.project=$COMPOSE_PROJECT_NAME" 2>/dev/null || echo "")

  if [[ -z "$container_id" ]]; then
    results+=("| $svc | FAIL | not running |")
    echo "preflight: $svc not running" >&2
    status=2
    continue
  fi

  # Check health status
  health=$(docker inspect --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}no-healthcheck{{end}}' "$container_id" 2>/dev/null || echo "unknown")

  case "$health" in
    healthy)
      results+=("| $svc | OK | healthy |")
      echo "preflight: $svc healthy" >&2
      ;;
    no-healthcheck)
      results+=("| $svc | OK | running (no healthcheck) |")
      echo "preflight: $svc running (no healthcheck)" >&2
      ;;
    starting)
      results+=("| $svc | WAIT | starting |")
      echo "preflight: $svc starting" >&2
      # Don't fail for starting services
      ;;
    *)
      results+=("| $svc | FAIL | $health |")
      echo "preflight: $svc health=$health" >&2
      status=2
      ;;
  esac
done

# ============================================================================
# WRITE OUTPUT
# ============================================================================

{
  echo "# Preflight Report"
  echo ""
  echo "**Time:** $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  echo "**Compose:** $COMPOSE_FILE"
  echo "**Project:** $COMPOSE_PROJECT_NAME"
  echo "**Status:** $([ $status -eq 0 ] && echo "PASS" || echo "FAIL")"
  echo ""
  echo "| Service | Status | Health |"
  echo "|---------|--------|--------|"
  for result in "${results[@]}"; do
    echo "$result"
  done
  echo ""
  if [[ $status -ne 0 ]]; then
    echo "## Action Required"
    echo ""
    echo "Start services with: \`make dev\`"
  fi
} > "$output_file"

exit "$status"
