#!/usr/bin/env bash
################################################################################
# session_start.sh - Claude Code Session Initialization
#
# Auto-detects project profile and generates .env.claude for deterministic
# execution. No hardcoded project names, compose files, or service lists.
#
# Exit codes:
#   0 - Success
#   (never fails - operates in degraded mode if detection fails)
################################################################################
set -euo pipefail

# ============================================================================
# PATHS
# ============================================================================

root_dir="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$root_dir"

claude_dir="$root_dir/.claude"
agent_dir="$root_dir/.claude/docs"
env_file="$claude_dir/.env.claude"
repo_map_script="$claude_dir/skills/project-navigation/scripts/repo_map.sh"

mkdir -p "$claude_dir" "$agent_dir"

# ============================================================================
# AUTO-DETECTION FUNCTIONS
# ============================================================================

detect_compose_file() {
  local candidates=(
    "docker-compose.yml"
    "docker-compose.yaml"
    "compose.yml"
    "compose.yaml"
    "infra/docker-compose.yml"
    "infra/docker-compose.yaml"
    "infra/compose.yml"
    "infra/compose.yaml"
    ".docker/docker-compose.yml"
    ".docker/docker-compose.yaml"
  )

  for candidate in "${candidates[@]}"; do
    if [[ -f "$root_dir/$candidate" ]]; then
      echo "$candidate"
      return 0
    fi
  done

  echo ""
  return 0
}

detect_compose_dev_file() {
  local base_file="$1"
  if [[ -z "$base_file" ]]; then
    echo ""
    return 0
  fi

  local dir
  dir="$(dirname "$base_file")"
  local basename
  basename="$(basename "$base_file")"

  # Try .dev variant
  local dev_candidates=()
  if [[ "$basename" == *.yml ]]; then
    dev_candidates+=("${dir}/${basename%.yml}.dev.yml")
    dev_candidates+=("${dir}/docker-compose.dev.yml")
  elif [[ "$basename" == *.yaml ]]; then
    dev_candidates+=("${dir}/${basename%.yaml}.dev.yaml")
    dev_candidates+=("${dir}/docker-compose.dev.yaml")
  fi

  for candidate in "${dev_candidates[@]}"; do
    if [[ -f "$root_dir/$candidate" ]]; then
      echo "$candidate"
      return 0
    fi
  done

  echo ""
  return 0
}

sanitize_project_name() {
  local name="$1"
  # Lowercase, replace non-alphanumeric with dash, remove leading/trailing dashes
  echo "$name" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g; s/^-*//; s/-*$//; s/--*/-/g'
}

detect_service() {
  local compose_file="$1"
  local patterns="$2"  # Space-separated list of patterns to try

  if [[ -z "$compose_file" ]] || [[ ! -f "$root_dir/$compose_file" ]]; then
    echo ""
    return 0
  fi

  local services
  services=$(docker compose -f "$root_dir/$compose_file" config --services 2>/dev/null || echo "")

  if [[ -z "$services" ]]; then
    echo ""
    return 0
  fi

  for pattern in $patterns; do
    if echo "$services" | grep -qx "$pattern"; then
      echo "$pattern"
      return 0
    fi
  done

  echo ""
  return 0
}

detect_search_tool() {
  if command -v rg >/dev/null 2>&1; then
    echo "rg"
  elif command -v grep >/dev/null 2>&1; then
    echo "grep"
  else
    echo ""
  fi
}

# ============================================================================
# MAIN: AUTO-DETECT AND GENERATE ENV
# ============================================================================

# Detect values
compose_file=$(detect_compose_file)
compose_dev_file=$(detect_compose_dev_file "$compose_file")
project_name=$(sanitize_project_name "$(basename "$root_dir")")
search_tool=$(detect_search_tool)
session_start=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Detect services only if compose file exists
api_service=""
web_service=""
if [[ -n "$compose_file" ]]; then
  api_service=$(detect_service "$compose_file" "backend api server app")
  web_service=$(detect_service "$compose_file" "web frontend client ui")
fi

# ============================================================================
# WRITE ENV FILE
# ============================================================================

cat > "$env_file" <<EOF
# Auto-generated by .claude/hooks/session_start.sh
# Generated: $session_start
#
# Override values by exporting before running Claude Code:
#   export COMPOSE_FILE=custom/compose.yml && claude

# Project
CLAUDE_PROJECT_ROOT=$root_dir
COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME:-$project_name}

# Compose (empty if not detected)
COMPOSE_FILE=${COMPOSE_FILE:-$compose_file}
COMPOSE_DEV_FILE=${COMPOSE_DEV_FILE:-$compose_dev_file}

# Services (empty if not detected)
API_SERVICE=${API_SERVICE:-$api_service}
WEB_SERVICE=${WEB_SERVICE:-$web_service}

# Preflight
PREFLIGHT_SERVICES=${PREFLIGHT_SERVICES:-}
PREFLIGHT_THROTTLE_SECONDS=${PREFLIGHT_THROTTLE_SECONDS:-15}

# Agent paths
AGENT_OUTPUT_ROOT=.claude/docs
KANBAN_ROOT=docs/kanban

# Tools
SEARCH_TOOL=$search_tool

# Session
SESSION_START=$session_start

# Backend Internal Key (extracted from ~/.bashrc, bypassing interactive guard)
BACKEND_INTERNAL_KEY=${BACKEND_INTERNAL_KEY:-$(grep -oP '(?<=export BACKEND_INTERNAL_KEY=").*(?=")' ~/.bashrc 2>/dev/null || echo "")}
EOF

# ============================================================================
# WRITE SESSION PROFILE SUMMARY (SHORT)
# ============================================================================

cat > "$agent_dir/session_profile.md" <<EOF
# Session Profile

| Key | Value |
|-----|-------|
| Started | $session_start |
| Project | $project_name |
| Compose | ${compose_file:-"(none)"} |
| API | ${api_service:-"(none)"} |
| Web | ${web_service:-"(none)"} |
EOF

# ============================================================================
# OPTIONAL: REFRESH REPO MAP
# ============================================================================

if [[ "${CLAUDE_REFRESH_REPO_MAP:-1}" == "1" ]] && [[ -x "$repo_map_script" ]]; then
  "$repo_map_script" > "$agent_dir/repo_map.md" 2>/dev/null || true
fi

# ============================================================================
# OBSERVABILITY: LOG SESSION START
# ============================================================================

metrics_script="$claude_dir/scripts/log-metrics.sh"
if [[ -x "$metrics_script" ]]; then
  export CLAUDE_SESSION_ID="${CLAUDE_SESSION_ID:-$(cat /proc/sys/kernel/random/uuid 2>/dev/null || date +%s)}"
  "$metrics_script" session_start \
    "project=$project_name" \
    "compose_file=${compose_file:-none}" \
    "api_service=${api_service:-none}" \
    "web_service=${web_service:-none}" \
    2>/dev/null || true
fi

# Success message to stderr (minimal)
echo "session_start: profile generated ($project_name)" >&2
