services:
  web:
    user: "${UID:-1000}:${GID:-1000}"         # corre como tu usuario, no root
    build:
      target: dev
    command: ["pnpm", "dev", "--hostname", "0.0.0.0", "--port", "3000"]  # ← aquí va
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8002}
      - DEEP_RESEARCH_ENABLED=${DEEP_RESEARCH_ENABLED:-true}
      - CI=true
    volumes:
      - ../package.json:/app/package.json:ro
      - ../pnpm-lock.yaml:/app/pnpm-lock.yaml:ro
      - ../pnpm-workspace.yaml:/app/pnpm-workspace.yaml:ro
      - ../packages:/app/packages
      - ../apps/web:/app/apps/web
      - web-next-cache:/app/apps/web/.next    # aísla .next en volumen docker

  api:
    environment:
      - DEEP_RESEARCH_ENABLED=${DEEP_RESEARCH_ENABLED:-true}

volumes:
  web-next-cache: {}   # definición del volumen, sin 'command' aquí

