services:
  web:
    user: "${UID:-1000}:${GID:-1000}"         # corre como tu usuario, no root
    build:
      target: dev
    command: ["pnpm", "dev", "--hostname", "0.0.0.0", "--port", "3000"]  # ← aquí va
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8001}
      - DEEP_RESEARCH_ENABLED=${DEEP_RESEARCH_ENABLED:-true}
      - CI=true
    volumes:
      - ../package.json:/app/package.json:ro
      - ../pnpm-lock.yaml:/app/pnpm-lock.yaml:ro
      - ../pnpm-workspace.yaml:/app/pnpm-workspace.yaml:ro
      - ../packages:/app/packages
      - ../apps/web:/app/apps/web
      # Anonymous volume for .next to prevent permission issues with Docker
      # This overrides the .next directory from the bind mount above
      - /app/apps/web/.next

  api:
    build:
      target: development  # Use development stage with pytest and testing tools
    volumes:
      # Mount source code for hot reload
      - ../apps/api/src:/app/src:ro
      - ../apps/api/tests:/app/tests:ro
    environment:
      - DEEP_RESEARCH_ENABLED=${DEEP_RESEARCH_ENABLED:-true}
      - PYTHONPATH=/app/src  # Add src to Python path for tests

