version: '3.8'

# Development override for docker-compose.yml
# Usage: docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d

services:
  # MongoDB with dev settings
  mongodb:
    environment:
      MONGO_INITDB_ROOT_USERNAME: copilotos_dev
      MONGO_INITDB_ROOT_PASSWORD: devpass123
    volumes:
      # Mount local data for development
      - ./data/mongodb:/data/db
      - ./logs/mongodb:/var/log/mongodb
    command: ["mongod", "--logpath", "/var/log/mongodb/mongod.log", "--logappend"]

  # Redis with dev settings
  redis:
    command: redis-server --appendonly yes --requirepass devpass123
    volumes:
      - ./data/redis:/data
      - ./logs/redis:/var/log/redis

  # Enable development tools by default
  mongo-express:
    profiles:
      - dev
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: copilotos_dev
      ME_CONFIG_MONGODB_ADMINPASSWORD: devpass123
      ME_CONFIG_MONGODB_URL: mongodb://copilotos_dev:devpass123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: dev
      ME_CONFIG_BASICAUTH_PASSWORD: dev123

  redis-commander:
    profiles:
      - dev
    environment:
      REDIS_PASSWORD: devpass123

  # Development API service (when ready)
  api:
    build:
      context: ../../apps/api
      dockerfile: Dockerfile.dev
    container_name: copilotos-api-dev
    ports:
      - "8000:8000"
    environment:
      MONGODB_URL: mongodb://copilotos_dev:devpass123@mongodb:27017/copilotos
      REDIS_URL: redis://:devpass123@redis:6379/0
      DEBUG: "true"
      LOG_LEVEL: debug
    volumes:
      - ../../apps/api:/app
      - /app/venv  # Exclude virtual environment
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - copilotos-network
    profiles:
      - dev

  # Development Web service (when ready)  
  web:
    build:
      context: ../../apps/web
      dockerfile: Dockerfile.dev
    container_name: copilotos-web-dev
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8000
      API_BASE_URL: http://api:8000
    volumes:
      - ../../apps/web:/app
      - /app/node_modules  # Exclude node_modules
      - /app/.next        # Exclude build cache
    depends_on:
      - api
    networks:
      - copilotos-network
    profiles:
      - dev